//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkall
    {
        public long id { get; set; }
        public string guid { get; set; }
        public Nullable<long> stt { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
        public string address { get; set; }
        public Nullable<long> user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_phone { get; set; }
        public Nullable<int> os { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> points { get; set; }
        public string province { get; set; }
        public Nullable<int> id_partner { get; set; }
        public string partner { get; set; }
        public string company { get; set; }
        public Nullable<int> code_company { get; set; }
        public string product_text { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> id_config_app { get; set; }
        public Nullable<int> waranty_year { get; set; }
        public string waranty_text { get; set; }
        public string waranty_link_web { get; set; }
        public string waranty_name { get; set; }
        public string waranty_phone { get; set; }
        public string waranty_address { get; set; }
    }
}
