//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_configapp_qrcode_link
    {
        public int id { get; set; }
        public Nullable<int> code_company { get; set; }
        public Nullable<int> id_config_app { get; set; }//Chính là id sản phẩm
        public Nullable<long> from_sn { get; set; }
        public Nullable<long> to_sn { get; set; }
    }
}
