//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_bonus_point
    {
        public int id { get; set; }
        public Nullable<int> check_point { get; set; }
        public Nullable<int> share_point { get; set; }
        public Nullable<int> ref_point { get; set; }
        public Nullable<int> time_point { get; set; }
    }
}
