//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sn_products
    {
        public long id { get; set; }
        public string sn { get; set; }
        public string guid { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> customer_code { get; set; }
        public string customer_name { get; set; }
        public string pin { get; set; }
        public Nullable<long> user_id { get; set; }
    }
}
